GoLang training: banking application
dominiclopes/BankingApplication pull request #2
Opened 2022-10-19 11:32 UTC by dominiclopes

2022-10-20 21:08 UTC, sushmitaw requested changes

2022-10-20 21:08 UTC, sushmitaw commented on go.mod
> +module example.com/banking
example.com is not appropriate module name , generally we use github.com/username/banking

2022-10-20 21:08 UTC, sushmitaw commented on go.mod
> +replace example.com/banking => /home/dominic/Documents/GoTrainingAtJosh/BankingApplication
replace directive should be used only in local , we do not have the destination path same on peer machine or prod

2022-10-20 21:08 UTC, sushmitaw commented on app/app.go
> +		return
add error log

2022-10-20 21:08 UTC, sushmitaw commented on app/app.go
> +		return
add error log

2022-10-20 21:08 UTC, sushmitaw commented on api/responses.go
> +func Error(rw http.ResponseWriter, status int, response interface{}) {
there is no difference between Success & error , when returning error we should send error msg , custom error code if neccessary

2022-10-20 21:08 UTC, sushmitaw commented on bank/handler.go
> +		if uAuth.Email == "" || uAuth.Password == "" {
create a new receiver method (l *LoginRequest) Validate() error {} put all the logic in thr .....

2022-10-20 21:08 UTC, sushmitaw commented on bank/handler.go
> +		http.SetCookie(rw, &http.Cookie{
generally we use authorization header to accept/set token , rather than cookie

2022-10-20 21:08 UTC, sushmitaw commented on bank/handler.go
> +		if accReq.Email == "" || accReq.PhoneNumber == "" {
same as above add validation method

2022-10-20 21:08 UTC, sushmitaw commented on bank/handler.go
> +		startDateTime, err := time.Parse("2006-01-02", transactionDetailsRequest.StartDate)
same as above

2022-10-20 21:08 UTC, sushmitaw commented on bank/service.go
> +func generateJWT(userID string, role string) (tokenString string, tokenExpirationTime time.Time, err error) {
add all jwt methods to utls

2022-10-20 21:08 UTC, sushmitaw commented on bank/service.go
> +func ValidateJWT(tokenString string) (claims *Claims, err error) {
add all jwt methods to utls

2022-10-20 21:08 UTC, sushmitaw commented on bank/service.go
> +	user, err := b.store.GetUserByEmailAndPassword(ctx, u.Email, u.Password)
save all personal data in encrypted form in db

2022-10-20 21:08 UTC, sushmitaw commented on bank/service.go
> +		PhoneNumber: accReq.PhoneNumber,
same as above

2022-10-21 06:50 UTC, dominiclopes commented on go.mod
> +replace example.com/banking => /home/dominic/Documents/GoTrainingAtJosh/BankingApplication
As I was using an incorrect module name, I had used the replace directive.
Removed this as we have updated for using the correct module name

2022-10-21 06:57 UTC, dominiclopes commented on app/app.go
> +		return
Updated, using logrus for logging the error and exiting the program. Thus, skipping the use of return

2022-10-21 06:57 UTC, dominiclopes commented on app/app.go
> +		return
Updated, using logrus for logging the error and exiting the program. Thus, skipping the use of return

2022-10-21 06:58 UTC, dominiclopes commented on go.mod
> +module example.com/banking
Updated the module name to `github.com/dominiclopes/BankingApplication`

2022-10-21 06:59 UTC, dominiclopes commented on api/responses.go
> +func Error(rw http.ResponseWriter, status int, response interface{}) {
Remove the duplicate code and updated the function name to APIResponse

2022-10-21 06:59 UTC, dominiclopes commented on bank/handler.go
> +		if uAuth.Email == "" || uAuth.Password == "" {
Updated, added the validations in a method, and using the same in the handler

2022-10-21 07:55 UTC, dominiclopes commented on bank/handler.go
> +		startDateTime, err := time.Parse("2006-01-02", transactionDetailsRequest.StartDate)
Added the validations in a method

2022-10-21 08:01 UTC, dominiclopes commented on bank/service.go
> +func generateJWT(userID string, role string) (tokenString string, tokenExpirationTime time.Time, err error) {
moved the jwt generate and validate functions to utils>jwt.go

2022-10-21 08:02 UTC, dominiclopes commented on bank/service.go
> +func ValidateJWT(tokenString string) (claims *Claims, err error) {
moved the jwt generate and validate functions to utils>jwt.go

2022-10-21 08:56 UTC, dominiclopes commented on bank/handler.go
> +		http.SetCookie(rw, &http.Cookie{
Updated - getting the token from the header instead of cookie

2023-02-21 04:25 UTC, merged